version: '1.0'

volumes:
  datafiles:

services:
  #DataBase Service
  database:
    image: mysql:8.0.22
    ports:
      - "3307:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: test
  #Api  Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development


# Navigate to http://localhost:5000/swagger/index.html in your browser for swagger documentation.