version: '2.0'

services:
  #DataBase Service
  database:
    image: mysql:8.0.22
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: "%"
  #Api  Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    depends_on:
      - database
    ports:
      - "8000:80"
      - "8001:443"
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - PASSWORD=${PASSWORD}


# Navigate to http://localhost:8000/api/v1/auth/doc/swagger/index.html in your browser for swagger documentation.